name: Update Badges

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily

jobs:
  update-badges:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install tomlkit
      run: pip install tomlkit

    - name: Update badges
      run: python .github/scripts/update_badges.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m 'Update badges'
        git push
